---
- name: Installing httpd
  hosts: all
  become: true
  tasks: 
  - name: Installing httpd
    yum: 
      name: httpd
      state: installed
    notify: start service httpd

  handlers:
  - name: start service httpd
    service:
      name: httpd
      state: started
